### ISSUE TITLE
Feedback for First Models/Views

### ISSUE THREAD

**Issue by camhelkuik** [camhelkuik/artist_organizer#14]

**Comment by sumeetjain** [comment]
- [x] Change your module's `find` method so that it returns an object. You shouldn't really need a `find_as_object` method in each of your classes (even though I know that's one of the ways I demonstrated it in class).
- [x] [Indentation](https://github.com/camhelkuik/artist_organizer/blob/master/models/application.rb#L44-L46)
- [x] Instead of referring to the instance variable (`@attribute`), use a reader method (like the ones `attr_reader` and `attr_accessor` give you). (https://github.com/camhelkuik/artist_organizer/blob/master/models/application.rb#L69-L74)
- [x] Should return an Array of custom Objects, not an Array of Hashes (https://github.com/camhelkuik/artist_organizer/blob/master/models/database_class_methods.rb#L70-L74) and (https://github.com/camhelkuik/artist_organizer/blob/master/models/database_class_methods.rb#L82-L86)
- [x] Instead of [this](https://github.com/camhelkuik/artist_organizer/blob/master/controllers/applications.rb#L40-L68), look into changing the HTML of the form so that it automatically sets the fields to their values. That way, if the user doesn't modify values, the existing value will be sent into `params`.

**Comment by sumeetjain** [comment]
- [x] Indentation issue remains (just one character off!)
- [x] Re: the reader methods instead of instance variables directly, one remains: https://github.com/camhelkuik/artist_organizer/blob/master/models/application.rb#L44
- [x] Some indentation issues in https://github.com/camhelkuik/artist_organizer/blob/master/models/database_class_methods.rb
